#[derive(Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Clone)]
pub enum StringSegment {
    String(String),
    Ident(String),
}

#[derive(Debug, PartialEq, Eq)]
pub enum Token {
    Ident(String),
    String(Vec<StringSegment>),
    Space(u8),
    Equal(u8),
    Bang(u8),
    Question(u8),
    Plus,
    PlusEq,
    Tack,
    TackEq,
    Star,
    StarEq,
    Slash,
    SlashEq,
    Percent,
    PercentEq,
    LCaret,
    LCaretEq,
    RCaret,
    RCaretEq,
    LParen,
    RParen,
    LSquirrely,
    RSquirrely,
    LSquare,
    RSquare,
    Arrow,
    Semicolon,
    Comma,
    Colon,
    Dot,
    And,
    Or,
}
